name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t devops-challenge-app .

      - name: Run Linter
        run: |
          docker run --name lint-check devops-challenge-app sh -c "npm install && npx eslint ."

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-challenge-app:latest
          
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: SSH into EC2 and Deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devopschallenge:latest
            docker stop app || true
            docker rm app || true
            docker run -d -p 80:80 --name app ${{ secrets.DOCKERHUB_USERNAME }}/devopschallenge:latest
          EOF
