name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t devops-challenge-app .

      - name: Run Linter
        run: |
          docker run --name lint-check devops-challenge-app sh -c "npm install && npm run lint"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: devopschallenge:latest
